apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: front-go
        image: ${Repo_Location}
        ports:
        - name: http-port
          containerPort: 8080
        resources:
          requests:
            cpu: 200m